### ISSUE TITLE
conflict with old version of laravel-admin

### ISSUE THREAD

**Issue by M0H3N** [FallenBG/stickies#1]
Hello
I have laravel-admin ver 1.5.12 ? 
Can I use this package ?

**Comment by FallenBG** [comment]
Hi,
I didn't do any tests with older versions but as I'm not relaying on any functionality from laravel-admin it should be OK to edit the dependencies.
Reading trough the laravel-admin the real backward compatibility will be 1.5.6 as then the navbar functionality was implemented.
https://laravel-admin.org/docs/#/en/custom-navbar?id=customize-the-head-navigation-bar

**Comment by FallenBG** [comment]
v0.2.1 downgrades the requirements for laravel-admin to 1.5.6
https://github.com/FallenBG/stickies/commit/eb4ca78992254efb7aa7511d7183ea44ef056fa0

Please do try and tell me if there are any issues.

Best Regards,
Martin

**Comment by M0H3N** [comment]
the package was installed but this time this error happened after installation :
``` 
Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In StickiesServiceProvider.php line 20:

  Call to undefined method Encore\Stickies\Stickies::boot()
```

**Comment by FallenBG** [comment]
Indeed, the parent function boot was introduced in laravel-admin 1.6.0 as were almost all functions used in ServiceProvider.

If you want to use the extension must upgrade to laravel-admin 1.6.0 (sorry bout that)

Closing the ticket with update of the composer.json.
https://github.com/FallenBG/stickies/commit/d56527f00ba5008fe6ebce312a1c8edfba40fc93
